-- MySQL Script generated by MySQL Workbench
-- sáb 21 nov 2020 10:10:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rastreamento_covid
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS rastreamento_covid ;

-- -----------------------------------------------------
-- Schema rastreamento_covid
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS rastreamento_covid ;
-- USE rastreamento_covid ;

-- -----------------------------------------------------
-- Table rastreamento_covid.usuario
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.usuario ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.usuario (
  usuario_id_ CHAR(32) NOT NULL,
  usuario_ord SERIAL UNIQUE NOT NULL,
  usuario_salt CHAR(32) NOT NULL,
  usuario_password CHAR(512) NOT NULL,
  usuario_primeiro_nome VARCHAR(45) NOT NULL,
  usuario_ultimo_nome VARCHAR(45) NOT NULL,
  usuario_consentimento BOOLEAN NOT NULL DEFAULT FALSE,
  usuario_data_nimento DATE NULL,
  PRIMARY KEY (usuario_id_));


-- -----------------------------------------------------
-- Table rastreamento_covid.email
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.email ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.email (
  email_id_ SERIAL NOT NULL,
  email_email VARCHAR(321) NOT NULL,
  email_usuario_id_ CHAR(32) NOT NULL,
  email_primario BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (email_id_),
  CONSTRAINT fk_email_usuario
    FOREIGN KEY (email_usuario_id_)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.telefone
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.telefone ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.telefone (
  telefone_id_ SERIAL NOT NULL,
  telefone_telefone CHAR(9) NOT NULL,
  telefone_usuario_id_ CHAR(32) NOT NULL,
  PRIMARY KEY (telefone_id_),
  CONSTRAINT fk_telefone_usuario
    FOREIGN KEY (telefone_usuario_id_)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.local
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.local ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.local (
  local_id_ CHAR(32) NOT NULL,
  local_ord SERIAL UNIQUE NOT NULL,
  local_nome VARCHAR(45) NOT NULL,
  local_longitude VARCHAR(45) NOT NULL,
  local_latitude VARCHAR(45) NOT NULL,
  PRIMARY KEY (local_id_));


-- -----------------------------------------------------
-- Table rastreamento_covid.checkin
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.checkin ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.checkin (
  checkin_id_ SERIAL NOT NULL,
  checkin_id_usuario CHAR(32) NOT NULL,
  checkin_local_id_ CHAR(32) NOT NULL,
  checkin_risco INT NOT NULL DEFAULT 0,
  checkin_inicio TIMESTAMP NOT NULL,
  checkin_final TIMESTAMP NULL,
  PRIMARY KEY (checkin_id_),
  CONSTRAINT fk_checkin_local
    FOREIGN KEY (checkin_local_id_)
    REFERENCES rastreamento_covid.local (local_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_checkin_usuario
    FOREIGN KEY (checkin_id_usuario)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.notificacao
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.notificacao ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.notificacao (
  notificacao_id_ SERIAL NOT NULL,
  notificacao_checkin_id_ INT NOT NULL,
  notificacao_hash_usuario CHAR(256) NOT NULL,
  notificacao_recebida BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (notificacao_id_),
  CONSTRAINT fk_notificacao_checkin
    FOREIGN KEY (notificacao_checkin_id_)
    REFERENCES rastreamento_covid.checkin (checkin_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.sintoma
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.sintoma ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.sintoma (
  sintoma_id_ SERIAL NOT NULL,
  sintoma_descricao VARCHAR(45) NOT NULL,
  sintoma_risco INT NOT NULL,
  PRIMARY KEY (sintoma_id_))
;


-- -----------------------------------------------------
-- Table rastreamento_covid.caso_sintoma
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.caso_sintoma ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.caso_sintoma (
  caso_sintoma_id_ CHAR(32) NOT NULL,
  caso_sintoma_usuario_id_ CHAR(32) NOT NULL,
  caso_sintoma_sintoma_id_ INT NOT NULL,
  caso_sintoma_inicio TIMESTAMP NOT NULL,
  caso_sintoma_final TIMESTAMP NULL,
  PRIMARY KEY (caso_sintoma_id_),
  CONSTRAINT fk_caso_sintoma_sintoma
    FOREIGN KEY (caso_sintoma_sintoma_id_)
    REFERENCES rastreamento_covid.sintoma (sintoma_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_caso_sintoma_usuario
    FOREIGN KEY (caso_sintoma_usuario_id_)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.medicamento
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.medicamento ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.medicamento (
  medicamento_id_ INT NOT NULL,
  medicamento_nome VARCHAR(45) NOT NULL,
  PRIMARY KEY (medicamento_id_))
;


-- -----------------------------------------------------
-- Table rastreamento_covid.medico
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.medico ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.medico (
  medico_id_ CHAR(32) NOT NULL,
  medico_nome VARCHAR(45) NOT NULL,
  PRIMARY KEY (medico_id_))
;


-- -----------------------------------------------------
-- Table rastreamento_covid.tratamento
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.tratamento ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.tratamento (
  tratamento_medicamento_id_ INT NOT NULL,
  tratamento_medico_id_ CHAR(32) NOT NULL,
  tratamento_usuario_id_ CHAR(32) NOT NULL,
  tratamento_posologia VARCHAR(45) NOT NULL,
  PRIMARY KEY (tratamento_medicamento_id_, tratamento_medico_id_, tratamento_usuario_id_),
  CONSTRAINT fk_medicamento_has_medico_medicamento1
    FOREIGN KEY (tratamento_medicamento_id_)
    REFERENCES rastreamento_covid.medicamento (medicamento_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_medicamento_has_medico_medico1
    FOREIGN KEY (tratamento_medico_id_)
    REFERENCES rastreamento_covid.medico (medico_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_tratamento_usuario
    FOREIGN KEY (tratamento_usuario_id_)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.hospital
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.hospital ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.hospital (
  hospital_id_ CHAR(32) NOT NULL,
  hospital_local VARCHAR(256) NOT NULL,
  hospital_nome VARCHAR(45) NOT NULL,
  PRIMARY KEY (hospital_id_))
;


-- -----------------------------------------------------
-- Table rastreamento_covid.contratacao
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.contratacao ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.contratacao (
  contratacao_medico_id_ CHAR(32) NOT NULL,
  contratacao_hospital_id_ CHAR(32) NOT NULL,
  PRIMARY KEY (contratacao_medico_id_, contratacao_hospital_id_),
  CONSTRAINT fk_medico_has_Hospital_medico1
    FOREIGN KEY (contratacao_medico_id_)
    REFERENCES rastreamento_covid.medico (medico_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_medico_has_Hospital_Hospital1
    FOREIGN KEY (contratacao_hospital_id_)
    REFERENCES rastreamento_covid.hospital (hospital_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.emissor
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.emissor ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.emissor (
  emissor_id_ INT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  local VARCHAR(256) NOT NULL,
  PRIMARY KEY (emissor_id_))
;


-- -----------------------------------------------------
-- Table rastreamento_covid.diagnostico
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.diagnostico ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.diagnostico (
  diagnostico_usuario_id_ CHAR(32) NOT NULL,
  diagnostico_emissor_id_ INT NOT NULL,
  diagnostico_data_exame DATE NOT NULL,
  diagnostico_data_inicio_sintomas DATE NOT NULL,
  diagnostico_data_fim_sintomas DATE NULL,
  diagnostico_data_recuperacao DATE NULL,
  PRIMARY KEY (diagnostico_usuario_id_, diagnostico_emissor_id_),
  CONSTRAINT fk_diagnostico_emissor1
    FOREIGN KEY (diagnostico_emissor_id_)
    REFERENCES rastreamento_covid.emissor (emissor_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_diagnostico_usuario
    FOREIGN KEY (diagnostico_usuario_id_)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table rastreamento_covid.internacao
-- -----------------------------------------------------
DROP TABLE IF EXISTS rastreamento_covid.internacao ;

CREATE TABLE IF NOT EXISTS rastreamento_covid.internacao (
  internacao_hospital_id_ CHAR(32) NOT NULL,
  internacao_usuario_id_ CHAR(32) NOT NULL,
  internacao_data_inicio DATE NOT NULL,
  internacao_uti BOOLEAN NOT NULL DEFAULT FALSE,
  internacao_alta DATE NULL,
  PRIMARY KEY (internacao_hospital_id_, internacao_data_inicio, internacao_usuario_id_),
  CONSTRAINT fk_internacao_hospital
    FOREIGN KEY (internacao_hospital_id_)
    REFERENCES rastreamento_covid.hospital (hospital_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_internacao_usuario
    FOREIGN KEY (internacao_usuario_id_)
    REFERENCES rastreamento_covid.usuario (usuario_id_)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
